env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: engine
    main: ./cmd/engine/main.go
    binary: engine
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - engine
    replacements:
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
